# Generated by Django 5.0.6 on 2024-07-08 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character_like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='character_like',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='episode_comment',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='episode_like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='episode_like',
            name='owner',
        ),
        migrations.CreateModel(
            name='Character_Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('character_id', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Episode_Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('episode_id', 'owner')},
            },
        ),
        migrations.DeleteModel(
            name='Character_Comment',
        ),
        migrations.DeleteModel(
            name='Character_Like',
        ),
        migrations.DeleteModel(
            name='Episode_Comment',
        ),
        migrations.DeleteModel(
            name='Episode_Like',
        ),
    ]
