# Generated by Django 5.0.6 on 2024-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_rating',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode_rating',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
