# Generated by Django 5.0.6 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character_rating_is_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_name',
            field=models.TextField(default=''),
        ),
    ]
