# Generated by Django 5.0.6 on 2024-07-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode_rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_name',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(default='/images/default_avatar.jpeg'),
        ),
    ]
